### PR TITLE
Add support for plv8 v1.5.0

### LINKED ISSUE #2: Support for plv8 1.5.x
plv8 1.5.x requires a newer version of V8 (4.3.66) which hasn't been made compatible with the `libv8-dev` Debian package yet. The last version available is 3.14.5, launched more than 3 years ago. Statically linking V8 by compiling with `make static` might be the only option going forward, but it requires about 3gb to build. The image would have to be slimmed down after compiling.

Potential diff:

`````` diff
diff --git c/9.5-1.5/Dockerfile i/9.5-1.5/Dockerfile
new file mode 100644
index 0000000..2632a2b
--- /dev/null
+++ i/9.5-1.5/Dockerfile
@@ -0,0 +1,12 @@
+FROM postgres:9.5
+MAINTAINER Chia-liang Kao <clkao@clkao.org>
+
+RUN apt-get update \
+       && apt-get install -y build-essential libv8-dev git-core postgresql-server-dev-$PG_MAJOR \
+       && rm -rf /var/lib/apt/lists/*
+
+ENV PLV8_BRANCH master
+
+RUN cd /tmp && git clone -b $PLV8_BRANCH https://github.com/plv8/plv8.git \
+  && cd /tmp/plv8 \
+  && make static install
diff --git c/9.5-1.5/README i/9.5-1.5/README
new file mode 100644
index 0000000..34fa3ab
--- /dev/null
+++ i/9.5-1.5/README
@@ -0,0 +1,19 @@
+# postgres-plv8
+
+Docker image for running plv8 1.5.x on Postgres 9.5.
+
+Based on the [official Postgres image](http://registry.hub.docker.com/_/postgres/).
+
+## Usage
+
+Start a postgres server container with persistent storage and give it a name:
+
+```bash
+$ docker run -d -v /tmp/data:/var/lib/postgresql/data --name some-postgres clkao/postgres-plv8:9.5
+```
+
+Start client container that links to the server container above as the "postgres" alias:
+
+```
+$ docker run --link some-postgres:postgres --rm -ti clkao/postgres-plv8:9.5 bash -c 'psql -U postgres -h $POSTGRES_PORT_5432_TCP_ADDR'
+```
``````

### PR DESCRIPTION
**Pull request by ruimarinho**
Closes #2.

Ideally, auto builds would be setup on hub.docker.com to tag these images appropriately. If you'd like, I can help with that too.

This PR introduces support for plv8 v1.5.0 for postgres 9.4 and 9.5. It also brings many improvements to plv8 v1.4.4 on both postgres versions, namely a considerable image size reduction by removing build dependencies and stripping symbols from the compiled plv8.so.

### CODE REVIEW

**Comment by ruimarinho** [comment]
@clkao pushed an updated to the README as from past experience, there's little to no benefit in keeping one for each subfolder. Hope you like it.

**Comment by clkao** [comment]
@ruimarinho++, I added you as collaborator on docker hub as well!  Please feel free to make changes for the 1.5 builds if you get a chance.

**Comment by ruimarinho** [comment]
Thanks @clkao! Glad to be part of this project! I'm trying to figure out how docker hub permissions work but information is scarce. It looks like I am listed as a contributor there but I can't actually edit anything on the repository (e.g. modify automated builds). Does this mean we would have to create an organization there? (postgres-plv8?)

**Comment by ruimarinho** [comment]
@clkao the build tags are still incorrect on Docker Hub. Any chance of taking a look at my previous comments? Thanks!

**Pull request merged**
