### PR TITLE
Fix PLV8_VERSION build directory suffix

### PR DESCRIPTION
**Pull request by ruimarinho**

### CODE REVIEW

**Comment by clkao** [comment]
This is for turning v2.0.0 to 2.0.0?

**Comment by ruimarinho** [comment]
This only fixes the `cd /tmp/build/plv8-v2.0.0` when it should have been `cd /tmp/build/plv8-2.0.0` when building. If you enable Travis we can get the build status tested instead of having a failure on Docker Cloud.

**Comment by clkao** [comment]
ok travis enabled.

**Comment by ruimarinho** [comment]
Awesome, thank you. Watching the master [build](https://travis-ci.org/clkao/docker-postgres-plv8/builds/198361253).

**Comment by clkao** [comment]
Since the 1.5 and 2.0 builds require building v8 from source, it might worth considering creating v8 images and use travis to build with volume-mount, and then push to docker hub from travis' after_success rather than relying on docker hub/cloud's build infrastructure.

**Comment by ruimarinho** [comment]
That sounds like a good idea, even though I don't expect many releases from PLV8.

**Pull request merged**
